# Generated by Django 3.2.8 on 2021-12-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211207_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videoUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
